name: Reusable amebadplus workflow template

on:
  workflow_call:
    # parameters from upstream workflow
    inputs:
      module_name:
        required: true
        type: string
      artifacts_name:
        required: true
        type: string
    # parameters from upstream inherit
    secrets:
      TOKEN_AMEBALITE:
        required: false
      TOKEN_AMEBASMART:
        required: false
      TOKEN_AMEBADPLUS:
        required: false

jobs:
  build-template-amebadplus:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Configure bash
      run: |
        sudo ln -sf /bin/bash /bin/sh

    - name: Configure prerequisites
      run: |
        # set config

        cd amebadplus_gcc_project

        if ${{ inputs.artifacts_name == 'amebadplus-B1' }}; then
          ./menuconfig.py -f menuconfig/confs_daily_build/bt1.conf menuconfig/confs_daily_build/audio_passthrough.conf
        fi

        if ${{ inputs.artifacts_name == 'amebadplus-B2' }}; then
          ./menuconfig.py -f menuconfig/confs_daily_build/high_tp.conf menuconfig/confs_daily_build/wps.conf
        fi

        if ${{ inputs.artifacts_name == 'amebadplus-B3' }}; then
          ./menuconfig.py -f menuconfig/confs_daily_build/bt2.conf menuconfig/confs_daily_build/usb.conf
        fi

        if ${{ inputs.artifacts_name == 'amebadplus-B5' }}; then
          ./menuconfig.py -f menuconfig/confs_daily_build/bt_en.conf menuconfig/confs_daily_build/mp_shrink.conf
        fi

        if ${{ inputs.artifacts_name == 'amebadplus-B6' }}; then
          ./menuconfig.py -f menuconfig/confs_daily_build/bt_en.conf menuconfig/confs_daily_build/mp_expand.conf
        fi

        cd -

    - name: Compile
      run: |
        cd amebadplus_gcc_project
        ./build.py
        cd -
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.artifacts_name }}
        path: |
          amebadplus_gcc_project/menuconfig/*.config
          amebadplus_gcc_project/menuconfig/*.config_km0
          amebadplus_gcc_project/menuconfig/*.config_km4
          amebadplus_gcc_project/project_km4/asdk/image
          amebadplus_gcc_project/project_km0/asdk/image
          amebadplus_gcc_project/project_km4/inc
          amebadplus_gcc_project/project_km0/inc