name: Validate Commit Message

on:
  pull_request:
    branches:
      - release/v1.0

jobs:
  check-commit-msg:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.sha }}
      - name: Get Commit Messages
        id: get_commits
        uses: josefpinegar/github-commit-messages@v1.0.0

      - name: Validate commit message
        if: ${{ steps.get_commits.outputs.messages != '' }}
        run: |
          echo "Commit messages:"
          echo "${{ steps.get_commits.outputs.messages }}"
          if echo "${{ steps.get_commits.outputs.messages }}" | grep "Change-Id:"; then
            echo "Valid commit message"
          else
            echo "Invalid commit message!!"
            exit 1
          fi